'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const script=html.match(/<script>\s*'use strict';([\s\S]*?)<\/script>/)[1];
function fn(name){const start=script.indexOf('function '+name+'(');let end=script.indexOf('\n}',start);return script.slice(start,end+2)}
function ctx(extra={}){return vm.createContext({console,Date,Map,Set,Number,encodeURIComponent,...extra})}
test('scan hist and archive preserve coin endpoints, price-only growth has no coin increase',()=>{const c=ctx();vm.runInContext(fs.readFileSync(__dirname+'/radar.js','utf8'),c);const w=c.OiRadar.scWindow(1,Date.parse('2026-10-04T12:00:00Z'));const r=c.OiRadar.scOiFromHist([{t:w.startMs,oiv:100,oi:10},{t:w.endMs,oiv:110,oi:10}],w);assert.equal(r.coinS,10);assert.equal(r.coinE,10);assert.equal((r.coinE/r.coinS-1)*100,0);const a=c.OiRadar.scOiFromArchive([{t:w.startMs-300000,oiv:100,oi:10},{t:w.endMs-300000,oiv:110,oi:10}],w);assert.equal(a.coinS,10);assert.equal(a.coinE,10);});
test('coin filters exclude unknown, notional increase distinct from coin increase',()=>{const c=ctx({S:{sc:{filter:'up',rows:[{sym:'A',net:10,coinNet:0,oiS:100,oiE:110},{sym:'B',net:10,coinNet:null,oiS:100,oiE:110}],sort:'sym',dir:1}}});vm.runInContext(fn('scFiltered'),c);assert.equal(c.scFiltered().length,1);c.S.sc.filter='in';assert.equal(c.scFiltered().length,2)});
test('fundingInfo failure leaves interval and OI unknown',async()=>{const els={};const c=ctx({API:'https://test',$:s=>els[s]||(els[s]={}),S:{fd:{loading:false},ov:{list:[{sym:'A',px:10,chg:0,vol:1}]},oi:new Map()},jget:async url=>{if(url.includes('fundingInfo'))throw Error('unavailable');return [{symbol:'A',lastFundingRate:'.0001',markPrice:'10',indexPrice:'10'}]},fdRender(){},fdMeta(){},ban(){}});vm.runInContext('async '+fn('fdLoad'),c);await c.fdLoad(true);assert.equal(c.S.fd.rows[0].interval,null);assert.equal(c.S.fd.rows[0].oiv,null)});
test('historical kline request includes encoded symbol and precise bounds',async()=>{let url;const c=ctx({API:'https://test',jget:async u=>(url=u,[])});vm.runInContext(fn('loadKlines'),c);await c.loadKlines('龙虾USDT',4,100,200);assert.ok(url.includes('startTime=100&endTime=200'));assert.ok(url.includes(encodeURIComponent('龙虾USDT')))});
test('stop cancels active requests and completed controls clean up',async()=>{let signal;const c=ctx({AbortController,setTimeout,clearTimeout,fetch:async(u,o)=>{signal=o.signal;return await new Promise((r,j)=>signal.addEventListener('abort',()=>j(Error('aborted'))))}});vm.runInContext('let apiCooldownUntil=0;const activeRequests=new Set();'+fn('abortActiveRequests')+'\n'+fn('fetchX'),c);const p=c.fetchX('x','json',1000);c.abortActiveRequests();await assert.rejects(p,/aborted/);assert.equal(signal.aborted,true)});
