'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const h=require('./hyperliquid.js');
const fixture=()=>[{universe:[{name:'BTC'},{name:'HYPE'},{name:'NOTHYPE'}]},[{markPx:'90000'},{markPx:'25',oraclePx:'24.9',prevDayPx:'20',openInterest:'100',funding:'-0.0001',premium:'0.002',dayNtlVlm:'123456',dayBaseVlm:'4321'},{markPx:'99'}]];
const patch=v=>{const f=fixture();Object.assign(f[1][1],v);return f};
test('only exact HYPE universe/context pair is selected',()=>{const r=h.parse(fixture());assert.equal(r.symbol,'HYPE');assert.equal(r.mark,25);assert.equal(r.oracle,24.9);assert.equal(r.return24h,25);assert.equal(r.openInterest,100);assert.equal(r.oiNotional,2500);assert.equal(r.funding,-.0001);assert.equal(r.premium,.002);assert.equal(r.dayNtlVlm,123456);assert.equal(r.dayBaseVlm,4321)});
test('all other perpetuals and ecosystem names excluded',()=>assert.equal(h.parse([{universe:[{name:'BTC'},{name:'HYPE-USDC'},{name:'hype'}]},[{},{},{}]]),null));
test('strict response shape and duplicate identities fail closed',()=>{for(const v of [null,{},[],[{universe:[]},{}],[{universe:[{name:'HYPE'}]},[]],[{universe:[{name:'HYPE'}]},[null]],[{universe:[{name:'HYPE'},{name:'HYPE'}]},[{},{}]]])assert.throws(()=>h.parse(v))});
test('missing empty negative or nonfinite unsigned fields remain unknown',()=>{for(const v of [null,undefined,'',' ','bad',Infinity,'Infinity',-1,true,{}]){const r=h.parse(patch({markPx:v,oraclePx:v,openInterest:v,dayNtlVlm:v,dayBaseVlm:v}));for(const k of ['mark','oracle','openInterest','dayNtlVlm','dayBaseVlm','oiNotional','return24h'])assert.equal(r[k],null)}});
test('zero is valid but cannot be previous-price divisor',()=>{const r=h.parse(patch({markPx:'0',prevDayPx:'0',openInterest:'0',funding:'0',dayNtlVlm:'0'}));assert.equal(r.mark,0);assert.equal(r.funding,0);assert.equal(r.oiNotional,0);assert.equal(r.return24h,null);assert.equal(r.dayNtlVlm,0)});
test('missing mark never replaced with oracle; arithmetic overflow unknown',()=>{assert.equal(h.parse(patch({markPx:null})).oiNotional,null);assert.equal(h.parse(patch({markPx:'1e308',openInterest:'1e308',prevDayPx:'1e-308'})).return24h,null);assert.equal(h.parse(patch({markPx:'1e308',openInterest:'1e308'})).oiNotional,null)});
test('signed funding premium and delisting visible',()=>{const f=patch({funding:'-0.1',premium:'-0.002'});f[0].universe[1].isDelisted=true;const r=h.parse(f);assert.equal(r.delisted,true);assert.equal(r.premium,-.002);assert.match(h.view({status:'ready',row:r,fetchedAt:100},100),/已下架/)});
test('POST info endpoint uses only public metaAndAssetCtxs body',async()=>{let called=0;const r=await h.request(async(url,opts)=>{called++;assert.equal(url,'https://api.hyperliquid.xyz/info');assert.equal(opts.method,'POST');assert.deepEqual(JSON.parse(opts.body),{type:'metaAndAssetCtxs'});assert.equal(opts.headers['Content-Type'],'application/json');assert.ok(opts.signal);return {ok:true,json:async()=>fixture()}});assert.equal(called,1);assert.equal(r.mark,25)});
test('HTTP network malformed JSON and abort errors reject',async()=>{await assert.rejects(h.request(async()=>({ok:false,status:429})),/HTTP 429/);await assert.rejects(h.request(async()=>{throw Error('network')}),/network/);await assert.rejects(h.request(async()=>({ok:true,json:async()=>{throw SyntaxError('JSON')}})),/JSON/);await assert.rejects(h.request(async()=>{throw Object.assign(Error('abort'),{name:'AbortError'})}),{name:'AbortError'})});
test('all UI states explicit, no missing-as-zero',()=>{for(const [status,text] of [['idle','尚未加载'],['loading','加载中'],['missing','未提供 HYPE 市场'],['error','读取失败']])assert.match(h.view({status,row:null,error:'',fetchedAt:0}),new RegExp(text));const html=h.view({status:'ready',row:h.parse(patch({markPx:null})),fetchedAt:100},100);assert.match(html,/标记价格<\/span><b>未知/);assert.match(html,/API 不是链上异动证据/);assert.match(html,/未返回结算周期/);assert.match(html,/不换算年化/);assert.match(html,/不构成交易建议/)});
test('old and failed snapshots cannot be labelled current',()=>{assert.match(h.view({status:'ready',row:h.parse(fixture()),fetchedAt:100},100+h.TTL+1),/旧行情/);assert.match(h.view({status:'error',row:h.parse(fixture()),fetchedAt:100,error:'failed'},101),/历史参考/)});
test('errors escaped instead of injecting markup',()=>{const html=h.view({status:'error',row:null,fetchedAt:0,error:'<img onerror="x">'});assert.doesNotMatch(html,/<img/);assert.match(html,/&lt;img/)});
function runtime(){
 const board={innerHTML:''},section={hidden:true,addEventListener(){}};let resolve,calls=0;
 const ctx={document:{querySelector:s=>s==='#hlBoard'?board:s==='#v-hype'?section:null,hidden:false},AbortController,Date,setTimeout,clearTimeout,setInterval(){},fetch:()=>{calls++;return new Promise(r=>resolve=r)}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/hyperliquid.js','utf8'),ctx);
 return {ctx,board,get calls(){return calls},reply:()=>resolve({ok:true,json:async()=>fixture()})};
}
test('UI loader coalesces requests and reuses fresh snapshot, force reload works',async()=>{const r=runtime(),a=r.ctx.hyperliquidLoad(),b=r.ctx.hyperliquidLoad();assert.equal(a,b);assert.equal(r.calls,1);assert.match(r.board.innerHTML,/加载中/);r.reply();await a;assert.equal(r.ctx.Hyperliquid.status,'ready');await r.ctx.hyperliquidLoad();assert.equal(r.calls,1);const c=r.ctx.hyperliquidLoad(true);assert.equal(r.calls,2);r.reply();await c});
test('failed reload keeps snapshot but flags error; retry recovers',async()=>{const r=runtime(),a=r.ctx.hyperliquidLoad();r.reply();await a;r.ctx.fetch=async()=>{throw Error('offline')};await r.ctx.hyperliquidLoad(true);assert.equal(r.ctx.Hyperliquid.status,'error');assert.equal(r.ctx.Hyperliquid.row.mark,25);assert.match(r.board.innerHTML,/历史参考/);r.ctx.fetch=async()=>({ok:true,json:async()=>fixture()});await r.ctx.hyperliquidLoad();assert.equal(r.ctx.Hyperliquid.status,'ready')});
test('missing universe response renders explicit missing state',async()=>{const r=runtime();r.ctx.fetch=async()=>({ok:true,json:async()=>[{universe:[]},[]]});await r.ctx.hyperliquidLoad();assert.equal(r.ctx.Hyperliquid.status,'missing');assert.equal(r.ctx.Hyperliquid.row,null)});
test('integration retains three primary entries and loads module before layout init',()=>{const html=fs.readFileSync(__dirname+'/index.html','utf8'),layout=fs.readFileSync(__dirname+'/layout.js','utf8');const nav=html.match(/<nav id="tabbar"[\s\S]*?<\/nav>/)[0];assert.equal((nav.match(/data-v=/g)||[]).length,3);assert.ok(html.indexOf('src="hyperliquid.js')>=0);assert.ok(html.indexOf('src="hyperliquid.js')<html.indexOf('src="layout.js'));assert.match(layout,/data-op="hype"/);assert.match(layout,/hyperliquidInit\(\)/);assert.match(layout,/k==='hype'.*hyperliquidLoad\(\)/);assert.match(layout,/for\(const id of \['strong','scan','signal'\]\).*op.append/)});
test('320px static guard: shrinking grids, single column, wrapping text and tabs',()=>{const css=fs.readFileSync(__dirname+'/hyperliquid.css','utf8');assert.match(css,/minmax\(0,1fr\)/);assert.match(css,/@media\(max-width:360px\)/);assert.match(css,/grid-template-columns:minmax\(0,1fr\)/);assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/font-size:11px;padding:8px 4px/);assert.doesNotMatch(css,/min-width:\s*\d{3,}px/)});
