'use strict';
const test=require('node:test'),a=require('node:assert/strict'),R=require('./oi-cap-radar');
const w=R.windowAt(Date.UTC(2026,9,5,12,3)),pair=(s=100,e=110)=>[{timestamp:w.start,sumOpenInterest:s,sumOpenInterestValue:1000},{timestamp:w.end,sumOpenInterest:e,sumOpenInterestValue:2000}];
test('window closes on common 5m boundaries and spans exactly one hour',()=>{a.equal(w.end-w.start,3600000);a.equal(w.end%300000,0);a.throws(()=>R.windowAt(NaN))});
test('OI growth uses coin quantity, ratio denominator uses notional USD separately',()=>{const r=R.sample(pair(),w);a.ok(Math.abs(r.growth-10)<1e-9);a.equal(r.notional,2000)});
test('missing duplicate or nearby endpoints cannot count as one hour',()=>{a.throws(()=>R.sample(pair().slice(1),w));const p=pair();p[1].timestamp--;a.throws(()=>R.sample(p,w));a.throws(()=>R.sample([...pair(),pair()[1]],w))});
test('invalid zero negative or nonfinite OI never becomes rank',()=>{for(const v of [0,-1,NaN,Infinity])a.throws(()=>R.sample(pair(v),w))});
test('only explicit asset IDs eligible; unknown same ticker and multiplier rejected',()=>{a.equal(R.identity('BTCUSDT').id,'bitcoin');a.equal(R.identity('AINUSDT'),null);a.equal(R.identity('1000SHIBUSDT'),null);a.equal(R.identity('BTCUSDC'),null)});
test('Top5 growth and market-cap ratio rankings remain independent',()=>{const rows=Array.from({length:7},(_,i)=>({sym:'S'+i,growth:i,ratio:6-i}));rows.push({sym:'MISSING',growth:50,ratio:null});const r=R.ranks(rows);a.equal(r.growth.length,5);a.equal(r.ratio.length,5);a.equal('resonance' in r,false);a.equal(r.growth[0].sym,'MISSING');a.ok(!r.ratio.some(x=>x.sym==='MISSING'))});
test('ratio may exceed 100 percent and missing ranks remain empty not zero',()=>{a.equal(R.ranks([{sym:'X',growth:-1,ratio:133.5}]).ratio[0].ratio,133.5);a.deepEqual(R.ranks([]),{growth:[],ratio:[]})});
function host(){return {innerHTML:'',addEventListener(){}}}
test('initialization is manual no requests until refresh',()=>{let n=0;R.init(host(),{fetchJSON:()=>n++});a.equal(n,0)});
test('real refresh dependency validates cache cap and exact maps',async()=>{const h=host(),x=R.init(h,{fetchJSON:async()=>cache()});await x.refresh();a.equal(x.state.rows.length,1);a.equal(x.state.rows[0].ratio,20);a.match(h.innerHTML,/BTC/)});
test('stale caps excluded while OI growth retained',async()=>{const d=cache();d.rows[0].capTime=d.generatedAt-20*60000;d.rows[0].ratio=null;const x=R.init(host(),{fetchJSON:async()=>d});await x.refresh();a.equal(x.state.rows.length,1);a.equal(x.state.rows[0].ratio,null)});
test('stopping discards pending results',async()=>{let resolve;const x=R.init(host(),{fetchJSON:()=>new Promise(r=>resolve=r)});const p=x.refresh();x.stop();resolve(cache());await p;a.equal(x.state.rows.length,0);a.equal(x.state.running,false)});
test('429 stops requests without retry loop or filling failures with zero',async()=>{let calls=0;const x=R.init(host(),{fetchJSON:async()=>{calls++;throw Object.assign(Error('HTTP 429'),{status:429})}});await x.refresh();a.equal(x.state.rows.length,0);a.match(x.state.capError,/限频/);const before=calls;await x.refresh();a.equal(calls,before)});

function cache(){const now=Date.now(),end=Math.floor(now/300000)*300000;return {schemaVersion:1,generatedAt:now,expiresAt:now+600000,publicationLagMs:now-end,window:{start:end-3600000,end},scope:{type:'quoteVolumeTop',limit:50,symbols:['BTCUSDT']},sources:{oi:'https://www.binance.com/futures/data/openInterestHist'},rows:[{sym:'BTCUSDT',coinStart:100,coinEnd:110,growth:(110/100-1)*100,notional:2000,marketCap:10000,capId:'bitcoin',capTime:now,ratio:999}],errors:[]}}
test('cache recalculates ratio and checks one-hour source and selection',()=>{const d=cache(),r=R.validateCache(d,Date.now(),50);a.equal(r.rows[0].ratio,20);a.throws(()=>R.validateCache(d,Date.now(),100));d.window.start++;a.throws(()=>R.validateCache(d,Date.now(),50))});
test('expired future duplicate or unregistered cache rows fail safely',()=>{for(const change of [d=>d.expiresAt=Date.now()-1,d=>d.generatedAt=Date.now()+120000,d=>d.rows.push(d.rows[0]),d=>d.rows[0].sym='ETHUSDT',d=>d.rows[0].growth=10+2]){const d=cache();change(d);a.throws(()=>R.validateCache(d,Date.now(),50))}});
test('unknown or stale market cap identity excluded not trusted from ratio',()=>{const d=cache();d.rows[0].capId='another-bitcoin';a.equal(R.validateCache(d,Date.now(),50).rows[0].ratio,null);d.rows[0].capId='bitcoin';d.rows[0].capTime=1;a.equal(R.validateCache(d,Date.now(),50).rows[0].ratio,null)});
test('cache refresh loads genuine supplied snapshot without browser external fetch',async()=>{const d=cache();let calls=0;const x=R.init(host(),{cacheURL:'oi-radar-live.json',getUniverse:()=>[],fetchJSON:async()=>{calls++;return d}});await x.refresh();a.equal(calls,1);a.equal(x.state.source,'官方API → 同源缓存');a.equal(x.state.updated,d.generatedAt);a.equal(x.state.rows[0].ratio,20)});
test('stop during cache request cannot apply old result',async()=>{let resolve;const x=R.init(host(),{cacheURL:'oi-radar-live.json',fetchJSON:()=>new Promise(r=>resolve=r)});const p=x.refresh();x.stop();resolve(cache());await p;a.equal(x.state.rows.length,0);a.equal(x.state.running,false)});

test('expired displayed snapshot removes both ranks instead of retaining stale claims',async()=>{const h=host(),x=R.init(h,{cacheURL:'oi-radar-live.json',fetchJSON:async()=>cache()});await x.refresh();a.equal(x.state.rows.length,1);x.state.expiresAt=Date.now()-1;x.expireSnapshot();a.equal(x.state.rows.length,0);a.match(h.innerHTML,/已过期/)});

test('worker collection UI stays in-app and reports progress',async()=>{const h=host();const x=R.init(h,{onCollect:true,fetchJSON:async url=>url.includes('/status/latest')?{run:{id:7,created_at:new Date().toISOString()}}:url.includes('/status?run=7')?{run:{id:7,status:'in_progress',created_at:new Date().toISOString()}}:cache()});a.match(h.innerHTML,/立即采集/);a.equal(h.innerHTML.includes('github.com'),false);a.equal(typeof x.collect,'function')});

function collectionFixture(){const h=host(),now=Date.now();let latest={id:6,created_at:new Date(now-10000).toISOString(),event:'workflow_dispatch'},run={id:7,status:'in_progress'},snapshot=cache(),posts=0;const x=R.init(h,{cacheURL:'cache.json',collectFetch:async(url,opt)=>{if(url.endsWith('/collect')){posts++;return Response.json({accepted:true,previousRunId:6,acceptedAt:now})}if(url.endsWith('/status/latest'))return Response.json({runs:[latest]});return Response.json({run})},fetchJSON:async()=>snapshot});return {h,x,now,get posts(){return posts},set latest(v){latest=v},set run(v){run=v},set snap(v){snapshot=v}}}
test('new collection never tracks previous completed run and waits Pages fresh cache',async()=>{const q=collectionFixture();await q.x.collect();a.equal(q.x.state.activeRunId,0);a.equal(q.x.state.collecting,true);await q.x.collect();a.equal(q.posts,1);q.latest={id:7,event:'workflow_dispatch',created_at:new Date(q.now).toISOString()};await q.x.checkRun();a.equal(q.x.state.activeRunId,7);a.match(q.h.innerHTML,/采集中/);q.run={id:7,status:'completed',conclusion:'success'};const old=cache();old.generatedAt=q.now-1000;q.snap=old;await q.x.checkRun();a.equal(q.x.state.collecting,true);a.match(q.h.innerHTML,/等待网页新缓存/);const fresh=cache();fresh.generatedAt=q.now+1;q.snap=fresh;await q.x.checkRun();a.equal(q.x.state.collecting,false);a.equal(q.x.state.updated,q.now+1);a.match(q.h.innerHTML,/榜单已更新/)});
test('failed run stops polling and never declares success',async()=>{const q=collectionFixture();q.latest={id:7,event:'workflow_dispatch',created_at:new Date(q.now).toISOString()};q.run={id:7,status:'completed',conclusion:'failure'};await q.x.collect();a.equal(q.x.state.collecting,false);a.match(q.h.innerHTML,/未成功/);a.equal(q.x.state.rows.length,0)});
test('stop invalidates waiting and explains cloud task not cancelled',async()=>{const q=collectionFixture();await q.x.collect();q.x.stop();a.equal(q.x.state.collecting,false);await q.x.checkRun();a.equal(q.posts,1);a.match(q.h.innerHTML,/云端采集未取消/)});
test('status error text escaped and bounded timeout stops local waiting',async()=>{const h=host(),x=R.init(h,{collectFetch:async u=>u.endsWith('/collect')?Response.json({previousRunId:6,acceptedAt:Date.now()}):Response.json({error:'<img onerror=alert(1)>'},{status:500})});await x.collect();a.doesNotMatch(h.innerHTML,/<img onerror/);a.match(h.innerHTML,/&lt;img/);x.state.collectStartedAt=Date.now()-13*60000;await x.checkRun();a.equal(x.state.collecting,false);a.match(h.innerHTML,/等待超时/)});

function historical(){const d=cache(),age=30*60000;d.generatedAt-=age;d.expiresAt-=age;d.window.start-=age;d.window.end-=age;d.rows[0].capTime-=age;return d}
test('expired valid snapshot is history only, never current ranking',async()=>{const h=host(),d=historical(),x=R.init(h,{fetchJSON:async()=>d});await x.refresh();a.equal(x.state.rows.length,0);a.equal(x.state.snapshotRows.length,1);a.match(h.innerHTML,/已过期，仅回看/);a.deepEqual(R.ranks(x.state.rows),{growth:[],ratio:[]});const e=x.getEvidence('BTCUSDT');a.equal(e.row,null);a.equal(e.snapshotRow.sym,'BTCUSDT');a.equal(e.fresh,false)});
test('expiry retains validated history but removes active rows',async()=>{const x=R.init(host(),{fetchJSON:async()=>cache()});await x.refresh();x.state.expiresAt=Date.now()-1;x.expireSnapshot();a.equal(x.state.rows.length,0);a.equal(x.state.snapshotRows.length,1);a.equal(x.getEvidence('BTCUSDT').current,false)});
test('over-two-hour future and bad-source snapshots rejected',()=>{for(const alter of [d=>d.generatedAt-=3*3600000,d=>d.generatedAt+=1000,d=>d.sources.oi='https://evil',d=>d.scope.symbols=['BTCUSDT','BTCUSDT']]){const d=cache();alter(d);a.throws(()=>R.validateSnapshot(d,Date.now(),50))}});
test('network failure preserves only independently valid historical snapshot',async()=>{let broken=false;const x=R.init(host(),{fetchJSON:async()=>{if(broken)throw Error('offline');return historical()}});await x.refresh();broken=true;await x.refresh();a.equal(x.state.rows.length,0);a.equal(x.state.snapshotRows.length,1);a.match(x.state.capError,/读取失败/)});
test('Chinese official symbol eligible and history dates are explicit',()=>{const d=cache();d.scope.symbols=['龙虾USDT'];d.rows[0]={...d.rows[0],sym:'龙虾USDT',marketCap:null,capTime:null,capId:null,ratio:null};a.equal(R.validateSnapshot(d,Date.now(),50).rows[0].sym,'龙虾USDT')});
