'use strict';
const test=require('node:test'),a=require('node:assert/strict'),R=require('./oi-cap-radar');
const w=R.windowAt(Date.UTC(2026,9,5,12,3)),pair=(s=100,e=110)=>[{timestamp:w.start,sumOpenInterest:s,sumOpenInterestValue:1000},{timestamp:w.end,sumOpenInterest:e,sumOpenInterestValue:2000}];
test('window closes on common 5m boundaries and spans exactly one hour',()=>{a.equal(w.end-w.start,3600000);a.equal(w.end%300000,0);a.throws(()=>R.windowAt(NaN))});
test('OI growth uses coin quantity, ratio denominator uses notional USD separately',()=>{const r=R.sample(pair(),w);a.ok(Math.abs(r.growth-10)<1e-9);a.equal(r.notional,2000)});
test('missing duplicate or nearby endpoints cannot count as one hour',()=>{a.throws(()=>R.sample(pair().slice(1),w));const p=pair();p[1].timestamp--;a.throws(()=>R.sample(p,w));a.throws(()=>R.sample([...pair(),pair()[1]],w))});
test('invalid zero negative or nonfinite OI never becomes rank',()=>{for(const v of [0,-1,NaN,Infinity])a.throws(()=>R.sample(pair(v),w))});
test('only explicit asset IDs eligible; unknown same ticker and multiplier rejected',()=>{a.equal(R.identity('BTCUSDT').id,'bitcoin');a.equal(R.identity('AINUSDT'),null);a.equal(R.identity('1000SHIBUSDT'),null);a.equal(R.identity('BTCUSDC'),null)});
test('Top5 positive growth and reliable ratio intersection exactly determines resonance',()=>{const rows=Array.from({length:7},(_,i)=>({sym:'S'+i,growth:i,ratio:6-i}));rows.push({sym:'MISSING',growth:50,ratio:null});const r=R.ranks(rows);a.equal(r.growth.length,5);a.equal(r.ratio.length,5);a.deepEqual(r.resonance,['S4','S3']);a.equal(r.growth[0].sym,'MISSING');a.ok(!r.ratio.some(x=>x.sym==='MISSING'))});
test('ratio may exceed 100 percent and missing ranks remain empty not zero',()=>{a.equal(R.ranks([{sym:'X',growth:-1,ratio:133.5}]).ratio[0].ratio,133.5);a.deepEqual(R.ranks([]),{growth:[],ratio:[],resonance:[]})});
function host(){return {innerHTML:'',addEventListener(){}}}
test('initialization is manual no requests until refresh',()=>{let n=0;R.init(host(),{fetchJSON:()=>n++});a.equal(n,0)});
test('real refresh dependency validates timestamp cap and exact maps',async()=>{const h=host();const x=R.init(h,{getUniverse:()=>[{sym:'BTCUSDT',vol:1}],fetchJSON:async url=>url.endsWith('/time')?{serverTime:w.end}:url.includes('coingecko')?{bitcoin:{usd_market_cap:10000,last_updated_at:Date.now()/1000}}:pair()});await x.refresh();a.equal(x.state.rows.length,1);a.equal(x.state.rows[0].ratio,20);a.match(h.innerHTML,/BTC/)});
test('stale caps excluded while OI growth retained',async()=>{const x=R.init(host(),{getUniverse:()=>[{sym:'BTCUSDT'}],fetchJSON:async url=>url.endsWith('/time')?{serverTime:w.end}:url.includes('coingecko')?{bitcoin:{usd_market_cap:10000,last_updated_at:1}}:pair()});await x.refresh();a.equal(x.state.rows[0].ratio,null)});
test('stopping discards pending results',async()=>{let resolve;const x=R.init(host(),{getUniverse:()=>[{sym:'BTCUSDT'}],fetchJSON:url=>url.endsWith('/time')?new Promise(r=>resolve=r):Promise.resolve(pair())});const p=x.refresh();x.stop();resolve({serverTime:w.end});await p;a.equal(x.state.rows.length,0);a.equal(x.state.running,false)});
test('429 stops batch without retry loop or filling failures with zero',async()=>{let calls=0;const x=R.init(host(),{getUniverse:()=>[{sym:'AINUSDT'},{sym:'AIOUSDT'}],fetchJSON:async url=>{if(url.endsWith('/time'))return {serverTime:w.end};calls++;throw Object.assign(Error('HTTP 429'),{status:429})}});await x.refresh();a.equal(x.state.rows.length,0);a.match(x.state.capError,/限频/);const before=calls;await x.refresh();a.equal(calls,before)});

function cache(){const now=Date.now(),end=Math.floor(now/300000)*300000;return {schemaVersion:1,generatedAt:now,expiresAt:now+600000,publicationLagMs:now-end,window:{start:end-3600000,end},scope:{type:'quoteVolumeTop',limit:50,symbols:['BTCUSDT']},sources:{oi:'https://www.binance.com/futures/data/openInterestHist'},rows:[{sym:'BTCUSDT',coinStart:100,coinEnd:110,growth:(110/100-1)*100,notional:2000,marketCap:10000,capId:'bitcoin',capTime:now,ratio:999}],errors:[]}}
test('cache recalculates ratio and checks one-hour source and selection',()=>{const d=cache(),r=R.validateCache(d,Date.now(),50);a.equal(r.rows[0].ratio,20);a.throws(()=>R.validateCache(d,Date.now(),100));d.window.start++;a.throws(()=>R.validateCache(d,Date.now(),50))});
test('expired future duplicate or unregistered cache rows fail safely',()=>{for(const change of [d=>d.expiresAt=Date.now()-1,d=>d.generatedAt=Date.now()+120000,d=>d.rows.push(d.rows[0]),d=>d.rows[0].sym='ETHUSDT',d=>d.rows[0].growth=10+2]){const d=cache();change(d);a.throws(()=>R.validateCache(d,Date.now(),50))}});
test('unknown or stale market cap identity excluded not trusted from ratio',()=>{const d=cache();d.rows[0].capId='another-bitcoin';a.equal(R.validateCache(d,Date.now(),50).rows[0].ratio,null);d.rows[0].capId='bitcoin';d.rows[0].capTime=1;a.equal(R.validateCache(d,Date.now(),50).rows[0].ratio,null)});
test('cache refresh loads genuine supplied snapshot without browser external fetch',async()=>{const d=cache();let calls=0;const x=R.init(host(),{cacheURL:'oi-radar-live.json',getUniverse:()=>[],fetchJSON:async()=>{calls++;return d}});await x.refresh();a.equal(calls,1);a.equal(x.state.source,'官方API → 同源缓存');a.equal(x.state.updated,d.generatedAt);a.equal(x.state.rows[0].ratio,20)});
test('stop during cache request cannot apply old result',async()=>{let resolve;const x=R.init(host(),{cacheURL:'oi-radar-live.json',fetchJSON:()=>new Promise(r=>resolve=r)});const p=x.refresh();x.stop();resolve(cache());await p;a.equal(x.state.rows.length,0);a.equal(x.state.running,false)});

test('expired displayed snapshot removes both ranks instead of retaining stale claims',async()=>{const h=host(),x=R.init(h,{cacheURL:'oi-radar-live.json',fetchJSON:async()=>cache()});await x.refresh();a.equal(x.state.rows.length,1);x.state.expiresAt=Date.now()-1;x.expireSnapshot();a.equal(x.state.rows.length,0);a.match(h.innerHTML,/已过期/)});

test('worker collection UI stays in-app and reports progress',async()=>{const h=host();const x=R.init(h,{onCollect:true,fetchJSON:async url=>url.includes('/status/latest')?{run:{id:7,created_at:new Date().toISOString()}}:url.includes('/status?run=7')?{run:{id:7,status:'in_progress',created_at:new Date().toISOString()}}:cache()});a.match(h.innerHTML,/立即采集/);a.equal(h.innerHTML.includes('github.com'),false);a.equal(typeof x.collect,'function')});
