'use strict';
const test=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync(__dirname+'/oi-radar-collector-worker.js','utf8').replace('export default','globalThis.worker=');
function fixture(opts={}){const calls=[],puts=[],c={URL,Response,Request,JSON,Number,Date,fetch:async(url,args)=>{calls.push({url,args});if(opts.error)throw Error('private secret must not leak');if(url.endsWith('/dispatches'))return new Response(null,{status:204});if(url.includes('/actions/runs/'))return Response.json({id:7,workflow_id:opts.wrong?99:5});if(url.endsWith('oi-radar-cache.yml'))return Response.json({id:5});return Response.json({workflow_runs:opts.busy?[{id:7,status:'queued'}]:[{id:6,status:'completed',event:'workflow_dispatch',created_at:'2026-10-06T00:00:00Z'}]})}};vm.createContext(c);vm.runInContext(code,c);const env={GITHUB_TOKEN:'fake-test-token',OI_RADAR_TRIGGER:{get:async()=>opts.last||null,put:async(...args)=>puts.push(args)}};return {calls,puts,run:(path,method='GET',body,origin='https://alchemyoo.github.io')=>c.worker.fetch(new Request('https://worker.test'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'1.2.3.4'},body:body===undefined?undefined:JSON.stringify(body)}),env)}}
test('invalid origin blocked without upstream request',async()=>{const x=fixture();a.equal((await x.run('/collect','POST',{},'https://evil.test')).status,403);a.equal(x.calls.length,0)});
test('preflight and unsupported route/method explicit',async()=>{const x=fixture();a.equal((await x.run('/collect','OPTIONS')).status,204);a.equal((await x.run('/collect')).status,405);a.equal((await x.run('/health')).status,404);a.equal((await x.run('/collect-data','POST',{})).status,404)});
test('limited Top50/100 dispatch fixed repo main never client-selected target',async()=>{const x=fixture();const r=await x.run('/collect','POST',{limit:100,repo:'evil',url:'evil'}),d=await r.json();a.equal(r.status,202);a.equal(d.previousRunId,6);a.ok(d.acceptedAt>0);const last=x.calls.at(-1);a.equal(last.url,'https://api.github.com/repos/Alchemyoo/oi-radar/actions/workflows/oi-radar-cache.yml/dispatches');a.deepEqual(JSON.parse(last.args.body),{ref:'main',inputs:{limit:'100'}});a.equal(x.puts.length,1)});
test('invalid limit and malformed body rejected before dispatch',async()=>{const x=fixture();a.equal((await x.run('/collect','POST',{limit:1})).status,400);a.equal((await x.run('/collect','POST')).status,400);a.equal(x.calls.length,0)});
test('cooldown rejects duplicate trigger',async()=>{const x=fixture({last:String(Date.now())});a.equal((await x.run('/collect','POST',{})).status,429);a.equal(x.calls.length,0)});
test('existing queued task is conflict not new dispatch',async()=>{const x=fixture({busy:true});a.equal((await x.run('/collect','POST',{})).status,409);a.equal(x.calls.length,1)});
test('status rejects invalid IDs and unrelated workflows',async()=>{const x=fixture({wrong:true});a.equal((await x.run('/status?run=abc')).status,400);a.equal((await x.run('/status?run=7')).status,403)});
test('specific run query verifies workflow identity',async()=>{const x=fixture();const r=await x.run('/status?run=7');a.equal(r.status,200);a.equal((await r.json()).run.id,7);a.equal(x.calls.length,2)});
test('latest is fixed workflow manual runs and errors are redacted',async()=>{const x=fixture();a.equal((await x.run('/status/latest')).status,200);a.match(x.calls[0].url,/event=workflow_dispatch/);const y=fixture({error:true}),r=await y.run('/status/latest');a.equal(r.status,502);a.doesNotMatch(await r.text(),/private|fake-test-token/)});
