'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c=require('./onchain.js'),now=Date.parse('2026-10-04T05:00:00Z');
const t={symbol:'TESTUSDT',chain:'bsc',chainId:56,address:'0x'+'a'.repeat(40)};
const row=()=>({identity:t,status:'ok',fetchedAt:new Date(now).toISOString(),txns:{h1:{buys:70,sells:30}},liquidityUsd:900000,liquidityChangePct:-10,liquidityBaselineAt:'2026-10-04T04:00:00Z',poolFingerprint:'f'.repeat(64)});
function channel(){return {status:'ok',identity:t,source:'https://provider.invalid/logs',fetchedAt:new Date(now).toISOString(),lastAttemptAt:new Date(now).toISOString(),window:{from:'2026-10-04T04:00:00Z',to:new Date(now).toISOString()},coverage:{complete:true,finality:'finalized'},events:[{tokenAddress:t.address,from:'0x'+'b'.repeat(40),to:'0x'+'c'.repeat(40),transactionHash:'0x'+'1'.repeat(64),blockHash:'0x'+'2'.repeat(64),blockNumber:100,logIndex:0,blockTime:'2026-10-04T04:30:00Z',finality:'finalized',removed:false,amountRaw:'100000000000000000000000',decimals:18,usdValue:100000,valuation:{source:'fixture',at:'2026-10-04T04:30:00Z'}}]}}
const withChannel=ch=>({...row(),evidence:{schemaVersion:1,transfers:ch}});
test('legacy rows have DEX evidence but no invented transfer coverage',()=>{const s=c.channelSummary(row(),t,now);assert.equal(s.dex.anomaly,true);assert.equal(s.transfers.state,'disabled');assert.equal(s.transfers.count,null);assert.match(s.dex.text,/含价格影响，非资金流/)});
test('verified finalized transfer logs are separate from DEX signals',()=>{const s=c.channelSummary({...withChannel(channel()),liquidityChangePct:0},t,now);assert.equal(s.dex.anomaly,false);assert.equal(s.transfers.anomaly,true);assert.equal(s.transfers.count,1)});
test('transfer channel timestamp is independent of DEX fetched time',()=>{const ch=channel();ch.fetchedAt=new Date(now-c.TTL-1).toISOString();ch.window={from:'2026-10-04T02:00:00Z',to:'2026-10-04T03:00:00Z'};ch.events[0].blockTime='2026-10-04T02:30:00Z';ch.events[0].valuation.at=ch.events[0].blockTime;const s=c.channelSummary(withChannel(ch),t,now);assert.equal(s.dex.state,'fresh');assert.equal(s.transfers.state,'stale');assert.equal(s.transfers.anomaly,false)});
test('missing USD pricing not classified as zero or large transfer',()=>{const ch=channel();ch.events[0].usdValue=null;delete ch.events[0].valuation;const s=c.channelSummary(withChannel(ch),t,now);assert.equal(s.transfers.count,0);assert.equal(s.transfers.anomaly,false);assert.match(s.transfers.text,/缺 USD 估值（不视为零）/)});
test('duplicates dedup but conflicts fail closed',()=>{const ch=channel();ch.events.push({...ch.events[0]});assert.equal(c.channelSummary(withChannel(ch),t,now).transfers.count,1);ch.events[1].usdValue=200000;assert.equal(c.channelSummary(withChannel(ch),t,now).transfers.state,'unavailable')});
test('identity finality coverage hash raw units and valuation fail closed',()=>{const changes=[{tokenAddress:'0x'+'f'.repeat(40)},{removed:true},{finality:'pending'},{amountRaw:100000},{decimals:true},{transactionHash:'javascript:alert(1)'},{usdValue:Infinity},{valuation:{source:'x',at:'2026-10-04T04:00:00Z'}},{blockTime:'2026-10-04T05:00:00Z'}];for(const change of changes){const ch=channel();Object.assign(ch.events[0],change);assert.equal(c.channelSummary(withChannel(ch),t,now).transfers.state,'unavailable')}for(const change of [{identity:{...t,chainId:1}},{coverage:{complete:false,finality:'finalized'}},{source:'https://u:p@provider.invalid'}]){assert.equal(c.channelSummary(withChannel({...channel(),...change}),t,now).transfers.state,'unavailable')}});
test('stale parent cache and future channel cannot confirm transfers',()=>{assert.equal(c.channelSummary({...withChannel(channel()),status:'stale'},t,now).transfers.state,'stale');assert.equal(c.channelSummary(withChannel({...channel(),fetchedAt:new Date(now+300001).toISOString()}),t,now).transfers.state,'unavailable')});
test('two panels produce safe transaction links and explicit disclaimers',()=>{const html=c.channelPanel(withChannel(channel()),t,now);assert.match(html,/data-oc-channel="dex"/);assert.match(html,/data-oc-channel="transfers"/);assert.match(html,/https:\/\/bscscan.com\/tx\/0x1+/);assert.match(html,/地址转账 ≠ 买卖/);assert.match(html,/不参与合约评分/);assert.doesNotMatch(html,/javascript:/)});
test('large DEX anomaly requires usable baseline fingerprint and thresholds',()=>{for(const changes of [{liquidityUsd:null},{liquidityUsd:9000},{poolFingerprint:'bad'},{liquidityBaselineAt:'bad'},{liquidityBaselineAt:'2026-10-04T04:59:00Z'},{status:'stale'}])assert.equal(c.channelSummary({...row(),...changes},t,now).dex.anomaly,false)});
test('evidence UI performs no requests or scans',()=>{let requests=0;const ctx={URL,fetch(){requests++;throw Error('no network')}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/onchain.js','utf8'),ctx);ctx.OnchainCore.channelPanel(withChannel(channel()),t,now);assert.equal(requests,0)});
test('registry UI accepts collector capacity 64 but rejects 65',()=>{const registry=n=>({schemaVersion:1,tokens:Array.from({length:n},(_,i)=>({...t,symbol:'TOKEN'+i+'USDT',sources:[{url:'https://official.invalid/evidence'}]}))});assert.equal(c.validateRegistry(registry(64)).length,64);assert.throws(()=>c.validateRegistry(registry(65)))});
test('recent fetch does not make an old event window current',()=>{const ch=channel();ch.window={from:'2026-10-04T02:00:00Z',to:'2026-10-04T03:00:00Z'};ch.events[0].blockTime='2026-10-04T02:30:00Z';ch.events[0].valuation.at=ch.events[0].blockTime;const s=c.channelSummary(withChannel(ch),t,now);assert.equal(s.transfers.state,'stale');assert.equal(s.transfers.anomaly,false)});
