'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const c=require('./onchain.js');
const now=Date.parse('2026-10-04T08:00:00Z'),address='0x'+'a'.repeat(40);
const identity={symbol:'龙虾USDT',chain:'bsc',chainId:56,address};
const row=()=>({identity,status:'ok',fetchedAt:new Date(now).toISOString(),txns:{h1:{buys:70,sells:30}}});
const registry=()=>({schemaVersion:1,tokens:[{...identity,sources:[{url:'https://www.binance.com/test',label:'官方'}]}]});
test('numeric missing is distinct from zero',()=>{for(const v of [null,undefined,'0',NaN,Infinity,-1,false])assert.equal(c.num(v),null);assert.equal(c.num(0),0)});
test('freshness per token not generated time',()=>{assert.equal(c.freshness(row(),now),'fresh');assert.equal(c.freshness({...row(),fetchedAt:new Date(now-c.TTL-1).toISOString()},now),'stale');assert.equal(c.freshness({...row(),status:'stale'},now),'stale')});
test('invalid and future snapshots unavailable',()=>{for(const r of [null,{...row(),fetchedAt:null},{...row(),fetchedAt:'bad'},{...row(),status:'error'},{...row(),fetchedAt:new Date(now+300001).toISOString()}])assert.equal(c.freshness(r,now),'unavailable')});
test('counts never interpreted as dollar flow',()=>{const b=c.countBias({buys:60,sells:40});assert.equal(b.text,'买入笔数偏多');assert.equal(b.kind,'up');assert.equal(b.share,.6);assert.equal(c.countBias({buys:40,sells:60}).text,'卖出笔数偏多')});
test('small zero missing or fractional samples neutral',()=>{for(const tx of [{buys:0,sells:0},{buys:1,sells:0},{buys:null,sells:4},{buys:.5,sells:20},{buys:Infinity,sells:20}])assert.equal(c.countBias(tx).kind,'neutral')});
test('fresh count bias and valid liquidity decline are evidence only',()=>{assert.equal(c.evidence(row(),now).text,'买入笔数偏多');assert.equal(c.evidence({...row(),liquidityChangePct:-12,liquidityBaselineAt:'2026-10-04T07:00:00Z'},now).text,'池流动性下降');assert.equal(c.evidence({...row(),liquidityChangePct:-12},now).text,'买入笔数偏多')});
test('stale rows cannot provide current directional evidence',()=>{const e=c.evidence({...row(),status:'stale',liquidityChangePct:-15,liquidityBaselineAt:'x'},now);assert.equal(e.text,'链上待更新');assert.equal(e.kind,'neutral')});
test('exact chain symbol and contract identity only',()=>{assert.equal(c.identity(identity,{...identity,address:address.toUpperCase().replace('0X','0x')}),true);for(const bad of [{...identity,chain:'ethereum'},{...identity,chainId:1},{...identity,symbol:'OTHERUSDT'},{...identity,address:'0x'+'b'.repeat(40)}])assert.equal(c.identity(identity,bad),false)});
test('registry validates Chinese contract symbols and rejects ambiguity',()=>{assert.equal(c.validateRegistry(registry()).length,1);assert.throws(()=>c.validateRegistry({schemaVersion:1,tokens:[...registry().tokens,...registry().tokens]}));assert.throws(()=>c.validateRegistry({schemaVersion:2,tokens:registry().tokens}));assert.throws(()=>c.validateRegistry({schemaVersion:1,tokens:[{...registry().tokens[0],address:'bad'}]}))});
test('snapshot cannot bind a fake same-name token',()=>{assert.equal(Object.keys(c.validateSnapshot({schemaVersion:1,tokens:{'龙虾USDT':row()}},c.validateRegistry(registry()))).length,1);assert.equal(Object.keys(c.validateSnapshot({schemaVersion:1,tokens:{'龙虾USDT':{...row(),identity:{...identity,address:'0x'+'b'.repeat(40)}}}},c.validateRegistry(registry()))).length,0)});
test('URLs require https with no embedded credentials',()=>{for(const url of ['javascript:alert(1)','http://example.com','https://user:pw@example.com','bad'])assert.equal(c.safeUrl(url),'');assert.equal(c.safeUrl('https://bscscan.com/token/0x123'),'https://bscscan.com/token/0x123')});
test('untrusted strings escaped',()=>assert.equal(c.escape('<img src="x">&\''),'&lt;img src=&quot;x&quot;&gt;&amp;&#39;'));
