'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const c=require('./onchain.js'),now=Date.parse('2026-10-04T08:00:00Z');
const t={symbol:'MUBARAKUSDT',chain:'bsc',chainId:56,address:'0x'+'a'.repeat(40)};
const row=(overrides={})=>({identity:t,status:'ok',fetchedAt:new Date(now).toISOString(),txns:{h1:{buys:70,sells:30}},...overrides});
const tag=r=>c.alertTag(t.symbol,[t],{[t.symbol]:r},now);
test('unmapped symbols explicitly lack verified coverage',()=>{for(const s of ['BTCUSDT','ETHUSDT','mubarakusdt','MUBARAK'])assert.equal(c.alertTag(s,[t],{[t.symbol]:row()},now),' · 未接入可验证链上数据')});
test('ordinary unmapped perpetual symbols fail closed',()=>{for(const s of ['BTCUSDT','ETHUSDT','SOLUSDT','UNKNOWNUSDT'])assert.equal(c.alertTag(s,[t],{[t.symbol]:row()},now),' · 未接入可验证链上数据')});
test('count bias is not a large monetary anomaly',()=>{assert.match(tag(row()),/链上笔数偏向:买入笔数偏多/);assert.match(tag(row({txns:{h1:{buys:40,sells:60}}})),/链上笔数偏向:卖出笔数偏多/);assert.match(tag(row()),/不是大额资金异动/)});
test('comparable liquidity drop threshold is reused',()=>{assert.match(tag(row({liquidityChangePct:-10,liquidityBaselineAt:'2026-10-04T07:00:00Z'})),/链上流动性下降证据/);assert.doesNotMatch(tag(row({liquidityChangePct:-9.99,liquidityBaselineAt:'2026-10-04T07:00:00Z'})),/池流动性下降/)});
test('neutral insufficient missing or zero samples are not anomalies',()=>{for(const tx of [{buys:50,sells:50},{buys:7,sells:3},{buys:0,sells:0},{buys:null,sells:40},null]){const text=tag(row({txns:{h1:tx}}));assert.match(text,/链上暂无可验证异动/);assert.doesNotMatch(text,/链上异动证据:/)}});
test('stale and failed snapshots do not assert current anomaly',()=>{for(const r of [row({status:'stale'}),row({fetchedAt:new Date(now-c.TTL-1).toISOString()})]){assert.match(tag(r),/旧快照待更新/);assert.doesNotMatch(tag(r),/链上异动证据:/)}assert.match(tag(row({status:'error'})),/有效快照暂无/)});
test('missing mismatched and future rows fail closed',()=>{for(const r of [null,row({identity:{...t,chainId:1}}),row({identity:{...t,address:'0x'+'b'.repeat(40)}}),row({fetchedAt:new Date(now+300001).toISOString()})]){assert.match(tag(r),/有效快照暂无/);assert.doesNotMatch(tag(r),/链上异动证据:/)}});
test('global helper uses cache without issuing any network call',()=>{let requests=0;const ctx={URL,fetch(){requests++;throw Error('unexpected request')}};vm.createContext(ctx);vm.runInContext(fs.readFileSync(__dirname+'/onchain.js','utf8'),ctx);ctx.Onchain.registry=[t];ctx.Onchain.rows={[t.symbol]:row({fetchedAt:new Date().toISOString()})};for(let i=0;i<100;i++)assert.match(ctx.onchainAlertTag(t.symbol),/买入笔数偏多/);assert.match(ctx.onchainBadge('BTCUSDT'),/未接入可验证链上数据/);assert.equal(requests,0)});
test('toast annotates strongest alert only before display without fetch',()=>{const html=fs.readFileSync(__dirname+'/index.html','utf8');const block=html.slice(html.indexOf('if(alerts.length){'),html.indexOf('S.rt.snapT=now;'));assert.ok(block.indexOf('onchainAlertTag(a.sym)')<block.indexOf('toast('));assert.match(block,/\$\{chainTag\}/);assert.match(block,/仅标注/);assert.doesNotMatch(block,/await|fetch\(|jget\(/)});
test('decorator adds explicit status for each table symbol, not only pilots',()=>{const js=fs.readFileSync(__dirname+'/onchain.js','utf8');const block=js.slice(js.indexOf('function decorate()'),js.indexOf('function renderDetail()'));assert.match(block,/badgeState\(sym\)/);assert.match(block,/b.textContent=state.text/);assert.doesNotMatch(block,/if\(!t\)continue/);assert.match(js,/root.onchainAlertTag=cachedAlertTag/);assert.match(js,/symbolIndex\(registry\)\.get\(sym\)/);assert.match(block,/if\(b\.textContent!==state.text\)/)});

test('large chain liquidity tag requires relative and absolute thresholds',()=>{const b={liquidityBaselineAt:'2026-10-04T07:00:00Z',txns:{h1:{buys:50,sells:50}}};assert.match(tag(row({...b,liquidityChangePct:-10,liquidityUsd:900000})),/链上异动:可比池流动性减少 \$100,000/);assert.match(tag(row({...b,liquidityChangePct:20,liquidityUsd:1200000})),/链上异动:可比池流动性增加/);for(const r of [{...b,liquidityChangePct:-10,liquidityUsd:9000},{...b,liquidityChangePct:9,liquidityUsd:10900000},{...b,liquidityChangePct:50,liquidityUsd:null}])assert.doesNotMatch(tag(row(r)),/链上异动:/);assert.match(tag(row({...b,liquidityChangePct:-10,liquidityUsd:900000})),/含价格影响，非资金流/)});
