'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=__dirname,html=fs.readFileSync(path.join(root,'index.html'),'utf8'),layout=fs.readFileSync(path.join(root,'layout.js'),'utf8');
test('release contains no removed data modules, badges or auxiliary requests',()=>{assert.doesNotMatch(html+'\n'+layout,/onchain|transfers\.js|chains\.js|ChainAdapters|链上|dexscreener|publicnode/i);assert.match(html,/<script>stBind\(false\);layoutInit\(\);window\.capRadar=OiCapRadar\.init/)});
test('retained page loads only Binance analytical scripts and keeps four workspaces',()=>{assert.deepEqual([...html.matchAll(/<script src="([^"?]+)/g)].map(m=>m[1]),['radar.js','rolling-oi.js','rolling-scan.js','strong.js','layout.js','oi-cap-radar.js','coin-evidence.js']);const nav=html.match(/<nav id="tabbar"[\s\S]*?<\/nav>/)[0];assert.equal((nav.match(/data-v=/g)||[]).length,4);for(const id of ['market','opportunity','signal','evidence'])assert.ok(nav.includes('data-v="'+id+'"'));assert.equal((layout.match(/data-op=/g)||[]).length,2)});
test('official OI cache workflow is explicit and removed data modules remain absent',()=>{const wf=fs.readFileSync(path.join(root,'.github/workflows/oi-radar-cache.yml'),'utf8');assert.match(wf,/schedule:/);assert.match(wf,/workflow_dispatch:/);assert.match(wf,/oi-cache-collector\.py/);assert.ok(fs.existsSync(path.join(root,'oi-cache-collector.py')));assert.equal(fs.existsSync(path.join(root,'data')),false);assert.equal(fs.existsSync(path.join(root,'scripts')),false)});

test('history page keeps original controls and table wrapper without cloning IDs',()=>{assert.match(layout,/evidenceView=layoutNode\('section','v-evidence'/);assert.match(layout,/card\.id='signalQuadPanel';evidenceView\.append\(card\)/);assert.match(layout,/signal\.append\(execCard\)/);assert.doesNotMatch(layout,/signal\.append\(execCard,quadCard\)|evidenceCard\.append\(\$\('#qdTbl'\)\)/);assert.match(layout,/signalHeading/);assert.match(layout,/oiMarketCapRadar/)});
test('history view participates in navigation and updated layout is cache-busted',()=>{assert.equal((layout.match(/\['market','opportunity','signal','evidence','detail'\]/g)||[]).length,2);assert.match(html,/layout\.js\?v=20261008-evidence1/);assert.doesNotMatch(layout,/signalEvidence/)});
