const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const c=require('./transfers.js');
const token={symbol:'TESTUSDT',chain:'bsc',chainId:56,address:'0x'+'a'.repeat(40)},hash='0x'+'b'.repeat(64),at='2026-10-04T13:00:00Z';
function fixture(){return {schemaVersion:1,tokens:{TESTUSDT:{identity:token,status:'ok',fetchedAt:at,decimals:18,decimalsSource:{method:'eth_call:decimals()',blockNumber:100,blockHash:hash},threshold:{kind:'token_units',units:'1000000',raw:'1000000000000000000000000',operator:'>='},coverage:{fromBlock:100,toBlock:100,complete:true,matchedCount:1,displayTruncated:false,fromTime:at,toTime:at},events:[{txHash:hash,blockHash:hash,blockNumber:100,logIndex:0,from:'0x'+'1'.repeat(40),to:'0x'+'2'.repeat(40),rawAmount:'1000000000000000000000000',eventTime:at,direction:'address_to_address',fromLabel:null,toLabel:null,usdValue:null}]}}}}
test('decimal thresholds and huge uint values remain exact',()=>{assert.equal(c.rawThreshold('1000000',18),10n**24n);assert.equal(c.rawThreshold('1.000001',6),1000001n);assert.equal(c.amount('1000000000000000000000001',18),'1000000.000000000000000001');assert.equal(c.amount('100',0),'100');assert.equal(c.amount('1000000000000000000',18),'1');assert.throws(()=>c.rawThreshold('1.1',0));assert.throws(()=>c.rawThreshold('0',18));});
test('strict identity, coverage, decimals and duplicate rejection',()=>{assert.equal(c.validate(fixture(),token).status,'ok');for(const change of [r=>r.identity={...token,address:'0x'+'c'.repeat(40)},r=>r.coverage.complete=false,r=>r.threshold.raw='1',r=>r.events.push({...r.events[0]}),r=>r.events[0].eventTime='2026-01-01T00:00:00Z',r=>r.events[0].direction='exchange_inflow',r=>r.decimalsSource=null,r=>r.coverage.matchedCount=0]){const data=fixture();change(data.tokens.TESTUSDT);assert.throws(()=>c.validate(data,token))}});
test('missing, stale and complete zero have distinct messaging',()=>{assert.match(c.render(null,token),/不可用/);const data=fixture();assert.equal(c.state(data.tokens.TESTUSDT,Date.parse(at)+91*60000),'stale');data.tokens.TESTUSDT.events=[];data.tokens.TESTUSDT.coverage.matchedCount=0;assert.match(c.render(data,token,Date.parse(at)),/完整查询范围内无/);assert.match(c.render(null,null),/未接入已核实链/)});
test('never trust arbitrary labels and never manufacture USD or exchange direction',()=>{const data=fixture();data.tokens.TESTUSDT.events[0].fromLabel={verified:true,label:'Binance <script>',url:'https://evil.example'};const html=c.render(data,token,Date.parse(at));assert.ok(!html.includes('Binance'));assert.ok(!html.includes('<script>'));assert.match(html,/标签未知/);assert.match(html,/USD 估值未知/);assert.match(html,/地址 → 地址/);assert.match(html,/https:\/\/bscscan.com\/tx/)});
test('unavailable records cannot carry events',()=>{const data=fixture();data.tokens.TESTUSDT.status='unknown';assert.throws(()=>c.validate(data,token));data.tokens.TESTUSDT.events=[];assert.match(c.render(data,token),/未知：decimals/)});
test('standalone page is cache only and does not attach contract scoring',()=>{const s=fs.readFileSync(__dirname+'/transfers.html','utf8');assert.ok(s.includes('transfers.js'));assert.ok(!s.includes('eth_getLogs'));assert.ok(!s.includes('stScore'));});

test('fresh fetch cannot revive old or future block window',()=>{const r=fixture().tokens.TESTUSDT;r.fetchedAt='2026-10-04T15:00:00Z';assert.equal(c.state(r,Date.parse(r.fetchedAt)),'stale');r.coverage.toTime='2026-10-04T16:00:00Z';assert.equal(c.state(r,Date.parse(r.fetchedAt)),'unavailable')});
test('main detail reads Transfer independently without claiming automated scans',()=>{const html=fs.readFileSync(__dirname+'/index.html','utf8'),js=fs.readFileSync(__dirname+'/onchain.js','utf8');assert.ok(html.indexOf('src="transfers.js')<html.indexOf('src="onchain.js'));assert.match(js,/transferCache=await getJson\('data\/transfers.json'/);assert.match(js,/TransferEvidence.render\(OC.transferCache,t\)/);assert.match(js,/不自动采集 Transfer/)});
