'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8'),MIN=60000,DAY=86400000,NOW=Date.UTC(2026,9,4,12),END=NOW;
function context(){
 const nodes=new Map(),c={MIN,DAY,API:'mock',Date:class extends Date{static now(){return NOW}},S:{id:{on:true,loading:false,generation:1,win:15,score:0,hist:new Map(),rows:[]},ov:{ready:true,list:[{sym:'XUSDT',vol:1}]},fd:{rows:[]},market:{bias:0},sc:{noHist:false},qd:{noHist:false}},QUADS:{trend:{name:'上涨增仓'},squeeze:{name:'下跌增仓'},flush:{name:'下跌减仓'},cover:{name:'上涨减仓'}},$:k=>{if(!nodes.has(k))nodes.set(k,{textContent:'',innerHTML:'',classList:{toggle(){}},style:{}});return nodes.get(k)},pool:async(a,n,f)=>{await Promise.all(a.map(f))},idMarketRender(){},idRender(){},toast(){},clearInterval(){},setInterval(){return 1},dstr:t=>new Date(t).toISOString().slice(0,10),utcToday0:()=>Date.UTC(2026,9,4)};
 vm.createContext(c);
 vm.runInContext(html.slice(html.indexOf('const QD_TH='),html.indexOf('async function qdGo('))+html.slice(html.indexOf('function idQuad('),html.indexOf('function loadKlines5('))+html.slice(html.indexOf('function idToggle('),html.indexOf("$('#idTbl').addEventListener")),c);
 return c;
}
function samples(win=60){return Array.from({length:win+1},(_,i)=>({t:END-(win-i)*MIN,v:100+i}));}
function bars(){return Array.from({length:40},(_,i)=>({t:END-(40-i)*5*MIN,c:100+i,h:101+i,l:99+i,v:10})).concat([{t:END,c:999,h:999,l:999,v:99}]);}
function mockPoll(c,fr){c.S.id.hist.set('XUSDT',samples());c.S.fd.time=NOW;c.S.fd.rows=fr==null?[]:[{sym:'XUSDT',fr,interval:8}];c.jget=async()=>({openInterest:'999',time:END+1});c.loadKlines5=async()=>bars();}
test('idWindow respects selected 15/30/60 minute endpoints',()=>{const c=context();for(const w of [15,30,60]){const r=c.idWindow(samples(),END,w);assert.equal(r.warmup,false);assert.ok(Math.abs(r.value-(160/(160-w)-1)*100)<1e-9)}});
test('idWindow does not borrow future endpoint or rounded future sample',()=>{const c=context(),a=samples().filter(x=>x.t<END);a.push({t:END,v:999,observedAt:END+1});const r=c.idWindow(a,END,15);assert.ok(Math.abs(r.value-(159/145-1)*100)<1e-9);assert.equal(c.idWindow(a.filter(x=>x.t<END-MIN),END,15).warmup,true)});
test('idWindow missing coverage and internal gaps cannot score',()=>{const c=context();assert.equal(c.idWindow(samples(5),END,15).value,null);assert.equal(c.idWindow(samples().filter(x=>x.t<END-10*MIN||x.t>END-5*MIN),END,15).value,null)});
test('intraday thresholds separate from daily five percent rule',()=>{const c=context();assert.equal(c.idQuad(1,.3),'trend');assert.equal(c.idQuad(.99,2),null);assert.equal(c.quadOf(1,1),null)});
test('actual idPoll closes price endpoints and ignores live future OI',async()=>{const c=context();mockPoll(c);await c.idPoll();const r=c.S.id.rows[0];assert.equal(r.t,END);assert.equal(r.px,139);assert.ok(Math.abs(r.dP-(139/136-1)*100)<1e-9);assert.ok(Math.abs(r.dOi-(160/145-1)*100)<1e-9);assert.equal(c.S.id.loading,false);assert.ok(Array.isArray(c.S.id.hist.get('XUSDT')))});
test('actual idPoll warms instead of scoring without coverage',async()=>{const c=context();mockPoll(c);c.S.id.hist.clear();await c.idPoll();assert.equal(c.S.id.rows.length,0);assert.match(c.S.id.coverage[0],/预热/)});
test('actual idPoll funding unknown contributes zero and fractional units correct',async()=>{const a=context(),b=context(),d=context();mockPoll(a);mockPoll(b,.0002);mockPoll(d,.0005);await a.idPoll();await b.idPoll();await d.idPoll();assert.equal(b.S.id.rows[0].score-a.S.id.rows[0].score,10);assert.equal(d.S.id.rows[0].score-a.S.id.rows[0].score,6)});
test('actual idPoll discards old generation samples/rows and cannot clear newer loading',async()=>{const c=context();mockPoll(c);let resolve;c.jget=()=>new Promise(r=>resolve=r);const p=c.idPoll();c.S.id.generation++;c.S.id.win=60;c.S.id.loading=true;c.S.id.rows=[{new:true}];c.S.id.hist.clear();resolve({openInterest:'999',time:END});await p;assert.equal(c.S.id.hist.size,0);assert.equal(c.S.id.rows[0].new,true);assert.equal(c.S.id.loading,true)});
test('actual idToggle stop invalidates in-flight poll',async()=>{const c=context();mockPoll(c);let resolve;c.jget=()=>new Promise(r=>resolve=r);const p=c.idPoll();c.idToggle(false);resolve({openInterest:'999',time:END});await p;assert.equal(c.S.id.hist.size,0);assert.equal(c.S.id.rows.length,0);assert.equal(c.S.id.loading,false)});
function history(c,future=999999){const zero=c.utcToday0();c.loadOiHist=async()=>Array.from({length:38},(_,i)=>({t:zero-(37-i)*DAY,oiv:100*Math.pow(1.1,i)})).concat([{t:zero+DAY,oiv:future}]);c.loadKlines=async()=>Array.from({length:38},(_,i)=>({t:zero-(38-i)*DAY,c:100*Math.pow(1.1,i)})).concat([{t:zero,c:future}]);}
test('actual qdOne win3 differs from day1 and compounds price at identical endpoints',async()=>{const c=context();history(c);const a=await c.qdOne('X',1),b=await c.qdOne('X',3);assert.ok(Math.abs(a.last.dP-10)<1e-8);assert.ok(Math.abs(b.last.dP-33.1)<1e-8);assert.ok(Math.abs(b.last.dOi-33.1)<1e-8);assert.equal(b.window,3);assert.equal(b.daily.length,30);assert.equal(b.stats.trend.n,29);assert.equal(b.daily.at(-1).ret,null);assert.ok(b.daily.every(x=>Math.abs(x.dP-33.1)<1e-8));assert.ok(Math.abs(b.stats.trend.sum/b.stats.trend.n-10)<1e-8)});
test('actual qdOne ignores future OI and unclosed next-day outcome',async()=>{const c=context();history(c,1);const a=await c.qdOne('X',3);history(c,1e12);const b=await c.qdOne('X',3);assert.equal(JSON.stringify(a),JSON.stringify(b))});
test('actual qdOne refuses missing consecutive day rather than shortening win3',async()=>{const c=context();history(c);const orig=c.loadOiHist;c.loadOiHist=async()=> (await orig()).filter(x=>x.t!==c.utcToday0()-DAY);assert.equal(await c.qdOne('X',3),null)});
test('actual window-change handler invalidates generation and keeps timestamp history',()=>{const c=context();mockPoll(c);const buttons=[{dataset:{w:'60'},classList:{toggle(){}}}],before=c.S.id.hist.get('XUSDT');c.$$=()=>buttons;c.idPoll=()=>{c.polled=true};const start=html.indexOf("  $$('#idWin button').forEach");vm.runInContext(html.slice(start,html.indexOf("  $$('#idScore button')",start)),c);buttons[0].onclick();assert.equal(c.S.id.win,60);assert.equal(c.S.id.generation,2);assert.equal(c.S.id.loading,false);assert.equal(c.S.id.rows.length,0);assert.equal(c.S.id.hist.get('XUSDT'),before);assert.equal(c.polled,true)});
test('actual qdOne archive path refuses truncated final day',async()=>{const c=context();history(c);c.S.qd.noHist=true;c.dailyEnd=rows=>rows.map(x=>({t:Math.floor(x.t/DAY)*DAY,oiv:x.oiv}));c.fetchDay=async(sym,d)=>[{t:Date.parse(d)+DAY-5*MIN,oiv:100*Math.pow(1.1,(Date.parse(d)-c.utcToday0())/DAY+40)}];assert.ok(await c.qdOne('X',3));c.fetchDay=async(sym,d)=>[{t:Date.parse(d)+DAY-10*MIN,oiv:100}];assert.equal(await c.qdOne('X',3),null)});

test('fundingEvidence rejects stale future unknown time and unknown cycle; unchanged fresh score',async()=>{for(const mutate of [c=>c.S.fd.time=NOW-16*MIN,c=>c.S.fd.time=NOW+2*MIN,c=>delete c.S.fd.time,c=>c.S.fd.rows[0].interval=null]){const x=context(),base=context();mockPoll(x,.0002);mockPoll(base);mutate(x);await x.idPoll();await base.idPoll();assert.equal(x.S.id.rows[0].fr,null);assert.equal(x.S.id.rows[0].score,base.S.id.rows[0].score)}const c=context();mockPoll(c,.0002);c.S.fd.rows[0].interval=1;const f=c.fundingEvidence('XUSDT');assert.equal(f.usable,true);assert.equal(f.intervalHours,1);await c.idPoll();assert.equal(c.S.id.rows[0].fundingInterval,1);assert.match(c.S.id.rows[0].state,/%\/1h/)});
test('historical CSV/card labels explicitly mean next-day upward proportion',()=>{assert.match(html,/次日上涨占比%/);assert.match(html,/次日上涨占比 <b>/);assert.doesNotMatch(html,/<th>胜率<\/th>| · 胜率 <b>/)});
